In [1]:
import numpy as np

## Creation functions

In [38]:
#1.array
b=[1,2,3,4,5,6,7,8,9,0]
c=np.array(b)
print(type(b))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [39]:
#2.zeros
a=np.zeros(5)
b=np.zeros((5,3))
print(a)
print('\n')
print(b)
    


[0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
#3.ones
a=np.ones(5)
b=np.ones((5,3))
print(a)
print('\n')
print(b)

[1. 1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
#4.empty

a=np.empty(4)
a

array([2.12199579e-314, 0.00000000e+000, 4.32801506e-321, 1.13952003e-311])

In [42]:
#5.arange
a=np.arange(4)
b=np.arange(1,10,3)
print(a)
print(b)

[0 1 2 3]
[1 4 7]


In [43]:
#6.linspace
a=np.linspace(1,10,)
b=np.linspace(1,10,5)
print(a)
print('\n')
print(b)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


[ 1.    3.25  5.5   7.75 10.  ]


In [37]:
#6. identity matrix
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array indexing and slicing

In [46]:
b=[1,2,3,4,5,6,7,8,9,0]
c=np.array(b)
print(c[1])
print('\n')
print(c[1:4])
print('\n')
print(c[1:6:2])


2


[2 3 4]


[2 4 6]


## Random number functions

In [48]:
l=np.array([1,2,3,4,4,5,6,6,7,8])
a=np.random.rand(5)
b=np.random.randn(5)
c=np.random.randint(5)
d=np.random.choice(l, size=4, replace=True, p=None)
print(a)
print('\n')
print(b)
print('\n')
print(c)
print('\n')
print(d)

[0.07982078 0.39898297 0.13191176 0.49099158 0.03774018]


[ 1.00793282 -0.62828657  1.2348316  -0.55654895 -1.20646346]


2


[6 5 6 4]


np.choice =
a: The array-like object from which to generate the random samples. It can be a 1-D array or a sequence.
size: The number of random samples to draw. If size is None (default), a single random element is returned. If an integer value is provided, an array with that many random elements is returned.
replace: A boolean flag that determines whether the samples are drawn with or without replacement. If True (default), elements can be drawn more than once. If False, each element can be drawn only once.
p: An optional array of probabilities associated with each element in a. It allows you to define custom probabilities for each element. The probabilities must sum up to 1. If p is not provided, all elements have an equal probability of being selected.

## Logical functions

In [49]:
# Example for np.logical_and()
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

result_and = np.logical_and(arr1, arr2)
print(result_and)  # Output: [ True False False False]


# Example for np.logical_or()
arr3 = np.array([True, True, False, False])
arr4 = np.array([True, False, True, False])

result_or = np.logical_or(arr3, arr4)
print(result_or)   # Output: [ True  True  True False]


# Example for np.logical_not()
arr5 = np.array([True, False, True, False])

result_not = np.logical_not(arr5)
print(result_not)  # Output: [False  True False  True]

[ True False False False]
[ True  True  True False]
[False  True False  True]


## Miscellaneous Functions

In [50]:
# Example for np.where()
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 30

result_where = np.where(condition, arr, -1)
print(result_where)  # Output: [-1 -1 -1 40 50]

# In this example, we use np.where() to create a new array where elements greater than 30 are replaced with their original value,
# and elements less than or equal to 30 are replaced with -1.


# Example for np.unique()
arr_unique = np.array([10, 20, 10, 30, 20, 40, 50])
unique_values = np.unique(arr_unique)
print(unique_values)  # Output: [10 20 30 40 50]

# In this example, we use np.unique() to find the unique elements in the array 'arr_unique' and return them in sorted order.


# Example for np.isin()
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([20, 50, 70])

result_isin = np.isin(arr1, arr2)
print(result_isin)  # Output: [False  True False False  True]

# In this example, we use np.isin() to check which elements of 'arr1' are also present in 'arr2'. It returns a boolean array
# indicating True for elements present in 'arr2' and False for elements not present in 'arr2'.

[-1 -1 -1 40 50]
[10 20 30 40 50]
[False  True False False  True]


## Mathematical functions


In [51]:
import numpy as np

# Create a parent array
arr = np.array([1, 2, 3, 4, 5])

# Example for np.add()
result_add = np.add(arr, 10)
print(result_add)  # Output: [11 12 13 14 15]

# Example for np.subtract()
result_subtract = np.subtract(arr, 3)
print(result_subtract)  # Output: [-2 -1  0  1  2]

# Example for np.multiply()
result_multiply = np.multiply(arr, 2)
print(result_multiply)  # Output: [ 2  4  6  8 10]

# Example for np.divide()
result_divide = np.divide(arr, 2)
print(result_divide)  # Output: [0.5 1.  1.5 2.  2.5]

# Example for np.power()
result_power = np.power(arr, 3)
print(result_power)  # Output: [  1   8  27  64 125]

# Example for np.sqrt()
result_sqrt = np.sqrt(arr)
print(result_sqrt)  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]

# Example for np.exp()
result_exp = np.exp(arr)
print(result_exp)  # Output: [ 2.71828183  7.3890561  20.08553692 54.59815003 148.4131591 ]

# Example for np.log()
result_log = np.log(arr)
print(result_log)  # Output: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

# Example for np.sin()
result_sin = np.sin(arr)
print(result_sin)  # Output: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

# Example for np.cos()
result_cos = np.cos(arr)
print(result_cos)  # Output: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

# Example for np.tan()
result_tan = np.tan(arr)
print(result_tan)  # Output: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


[11 12 13 14 15]
[-2 -1  0  1  2]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[  1   8  27  64 125]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


## Statistical functions

In [56]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.mean())
print('\n')
b=np.median(arr)
print(b)
print('\n')
print(arr.sum())
print('\n')
print(arr.min())
print('\n')
print(arr.max())
print('\n')
print(arr.var())#variance
print('\n')
print(arr.std())
print('\n')
percentile_value = np.percentile(arr, 25)
print(percentile_value)


3.0


3.0


15


1


5


2.0


1.4142135623730951


2.0


## Array manipulation

In [57]:
import numpy as np

# Example for np.dot() - Dot Product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)
print(dot_product)
# Output: [[19 22]
#          [43 50]]

# Example for np.matmul() - Matrix Multiplication
matrix_product = np.matmul(arr1, arr2)
print(matrix_product)
# Output: [[19 22]
#          [43 50]]


# Example for np.linalg.inv() - Inverse of a matrix
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)
# Output: [[-2.   1. ]
#          [ 1.5 -0.5]]


# Example for np.linalg.det() - Determinant of a matrix
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print(determinant)
# Output: -2.0


# Example for np.linalg.eig() - Eigenvalues and eigenvectors of a matrix
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
# Output: [-0.37228132  5.37228132]

print("Eigenvectors:")
print(eigenvectors)
# Output: [[-0.82456484 -0.41597356]
#          [ 0.56576746 -0.90937671]]


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Array manipulation

In [58]:
import numpy as np

# Example for np.ravel() - Flatten a multi-dimensional array to a 1-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = np.ravel(arr)
print(flattened_arr)  # Output: [1 2 3 4 5 6]


# Example for np.flatten() - Flatten a multi-dimensional array to a 1-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)  # Output: [1 2 3 4 5 6]


# Example for np.squeeze() - Remove single-dimensional entries from the shape of an array
arr = np.array([[[1], [2], [3]]])
squeezed_arr = np.squeeze(arr)
print(squeezed_arr)  # Output: [[1]
                     #          [2]
                     #          [3]]


# Example for np.expand_dims() - Add a new axis (dimension) to an array
arr = np.array([1, 2, 3])
expanded_arr = np.expand_dims(arr, axis=1)
print(expanded_arr)
# Output:
# [[1]
#  [2]
#  [3]]


# Example for np.stack() - Stack arrays along a new axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]


# Example for np.split() - Split an array into multiple sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 3)
print(sub_arrays)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


# Example for np.tile() - Construct an array by repeating an existing array
arr = np.array([1, 2, 3])
tiled_arr = np.tile(arr, 3)
print(tiled_arr)  # Output: [1 2 3 1 2 3 1 2 3]


# Example for np.repeat() - Repeat elements of an array
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 3)
print(repeated_arr)  # Output: [1 1 1 2 2 2 3 3 3]


# Example for np.delete() - Delete elements from an array
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [0, 2])  # Delete elements at index 0 and 2
print(new_arr)  # Output: [2 4 5]


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]
[2 4 5]


## Aggregate functions

In [60]:
import numpy as np

# Example for np.any() - Check if any element in the array is True (non-zero)
arr1 = np.array([0, 0, 0, 1, 0])
arr2 = np.array([0, 0, 0, 0, 0])

result_any1 = np.any(arr1)
result_any2 = np.any(arr2)

print(result_any1)  # Output: True (at least one element is True)
print(result_any2)  # Output: False (all elements are False)


# Example for np.all() - Check if all elements in the array are True (non-zero)
arr3 = np.array([1, 1, 1, 1, 1])
arr4 = np.array([1, 0, 1, 1, 1])

result_all1 = np.all(arr3)
result_all2 = np.all(arr4)

print(result_all1)  # Output: True (all elements are True)
print(result_all2)  # Output: False (one element is False)


# Example for np.nonzero() - Get the indices of non-zero elements in the array
arr5 = np.array([0, 1, 0, 2, 0, 3])

nonzero_indices = np.nonzero(arr5)
print(nonzero_indices)  # Output: (array([1, 3, 5]),)
# The function returns a tuple containing the indices of non-zero elements.


# Example for np.argmax() - Get the index of the maximum value in the array
arr6 = np.array([10, 5, 30, 15, 20])

max_index = np.argmax(arr6)
print(max_index)  # Output: 2 (index of the maximum value, which is 30 at index 2)


# Example for np.argmin() - Get the index of the minimum value in the array
arr7 = np.array([10, 5, 30, 15, 20])

min_index = np.argmin(arr7)
print(min_index)  # Output: 1 (index of the minimum value, which is 5 at index 1)


True
False
True
False
(array([1, 3, 5], dtype=int64),)
2
1


## Advanced mathematical functions

In [62]:
import numpy as np

# Example for np.fft - Fast Fourier Transform
arr = np.array([1, 2, 3, 4, 5])
fft_result = np.fft.fft(arr)
print(fft_result)
# Output: [15. -2.5+3.4409548j -2.5+0.81229924j -2.5-0.81229924j -2.5-3.4409548j 10. ]
# The output is the complex Fourier transform of the input array.


# Example for np.linalg.norm() - Calculate various vector norms
arr = np.array([3, 4])
norm_l2 = np.linalg.norm(arr)
print(norm_l2)  # Output: 5.0
# The output is the L2 (Euclidean) norm of the vector [3, 4].


# Example for np.random.seed() - Set the random seed for reproducibility
np.random.seed(42)
random_arr1 = np.random.rand(3)
print(random_arr1)
# Output: [0.37454012 0.95071431 0.73199394]

np.random.seed(42)  # Resetting the seed
random_arr2 = np.random.rand(3)
print(random_arr2)
# Output: [0.37454012 0.95071431 0.73199394]
# The two arrays 'random_arr1' and 'random_arr2' will be the same because of the seed set.


# Example for np.clip() - Clip (limit) the values in an array
arr = np.array([1, 2, 3, 4, 5])
clipped_arr = np.clip(arr, 2, 4)
print(clipped_arr)  # Output: [2 2 3 4 4]
# The values in the array are clipped to be between 2 and 4.



[15. +0.j         -2.5+3.4409548j  -2.5+0.81229924j -2.5-0.81229924j
 -2.5-3.4409548j ]
5.0
[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
[2 2 3 4 4]


## Statistical functions

In [63]:
import numpy as np

# Example for np.histogram() - Compute the histogram of an array
arr = np.array([1, 2, 1, 3, 4, 2, 5, 3, 3])
hist, bins = np.histogram(arr, bins=[0, 1, 2, 3, 4, 5])
print("Histogram:", hist)  # Output: [0 2 3 3 1]
print("Bins:", bins)  # Output: [0 1 2 3 4 5]
# The output is the histogram values and the bin edges.


# Example for np.cov() - Compute the covariance matrix of two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
cov_matrix = np.cov(arr1, arr2)
print(cov_matrix)
# Output:
# [[ 2.5 -2.5]
#  [-2.5  2.5]]
# The output is the covariance matrix of 'arr1' and 'arr2'.


# Example for np.correlate() - Cross-correlation of two 1-dimensional sequences
arr3 = np.array([1, 2, 3])
arr4 = np.array([0, 1, 0.5])
correlation = np.correlate(arr3, arr4, mode='valid')
print(correlation)  # Output: [3.5]
# The output is the cross-correlation value between 'arr3' and 'arr4' with valid mode.


Histogram: [0 2 2 3 2]
Bins: [0 1 2 3 4 5]
[[ 2.5 -2.5]
 [-2.5  2.5]]
[3.5]


## Broadcasting

Broadcasting in NumPy is a powerful feature that allows arrays with different shapes to be combined in arithmetic operations, even if their shapes are not compatible according to traditional array arithmetic rules.Broadcasting allows you to perform operations between arrays with different shapes without having to explicitly reshape or tile the arrays, which can significantly improve code readability and efficiency.

In [64]:
import numpy as np

# Broadcasting example
a = np.array([1, 2, 3])
b = 10

result = a + b
print(result)  # Output: [11 12 13]


[11 12 13]


## Fancy indexing

Fancy indexing in NumPy refers to an advanced indexing technique where an array can be indexed or sliced using an array of integers or boolean values (or a combination of both) instead of simple scalars or slices. Fancy indexing allows you to select specific elements or subsets of elements from an array based on the indices or boolean conditions specified in another array.

Integer Array Indexing:
You can pass an array of integers as indices to select specific elements from the original array.

In [65]:
import numpy as np

# Integer Array Indexing example
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
selected_elements = arr[indices]
print(selected_elements)  # Output: [10 30 50]


[10 30 50]


Boolean Array Indexing (Boolean Masking):
You can pass an array of boolean values as a mask to select elements from the original array where the corresponding mask value is True

In [66]:
import numpy as np

# Boolean Array Indexing (Boolean Masking) example
arr = np.array([10, 20, 30, 40, 50])
mask = np.array([False, True, False, True, False])
selected_elements = arr[mask]
print(selected_elements)  # Output: [20 40]


[20 40]


## Masked arrays

In [67]:
import numpy as np

# Create a regular NumPy array
data = np.array([1, 2, 3, -999, 5, 6, -999, 8, 9])

# Create a mask for invalid values (e.g., -999)
mask = data == -999

# Create a masked array using the original data and mask
masked_data = np.ma.masked_array(data, mask)

# Perform computations with the masked array
mean = np.ma.mean(masked_data)
print(mean)  # Output: 4.714285714285714 (ignoring the masked elements)


4.857142857142857


## Vectorization

In [68]:
import numpy as np

# Non-vectorized approach using a loop
arr = np.array([1, 2, 3, 4, 5])
result = np.zeros_like(arr)
for i in range(len(arr)):
    result[i] = arr[i] * 2

print(result)  # Output: [ 2  4  6  8 10]

# Vectorized approach using NumPy
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2

print(result)  # Output: [ 2  4  6  8 10]


[ 2  4  6  8 10]
[ 2  4  6  8 10]
